<?php

return [
	'salutation' => ['Mr', 'Miss', 'Mrs', 'Dr', 'Prof'],

	'document_type' => [
		'PSC 2 Form',
		'Birth Certificate',
		'National ID card (both sides)',
		'Civil Servant ID card (both sides)',
		'Personal Identification Number (KRA-PIN)',
		'PCA on first Appointment /GP 24 Revised',
		'Letter of First Appointment',
		'Letter of confirmation in appointment',
		'Contract letter',
		'All Promotion Letters',
		'Re-designation/ Re grading Letter',
		'Unpaid Leave Letter',
		'Secondment Letter',
		'Transfer of Service Letter',
		'Professional and Academic certificates',
		'Current Passport photo',
		'Disability (if any Registration Certificate)',
		'Next of Kin (GP.25)',
		'Displinary Letter',
		'Others'
	],

	'religion' => [
		"Christianity",
		"Islam",
		"Traditional African Religions",
		"Hinduism",
		"Buddhism",
		"Baha'i Faith",
		"Judaism",
		"No religion"
	],

	'blood_type' => [
		"A+",
		"A-",
		"B+",
		"B-",
		"AB+",
		"AB-",
		"O+",
		"O-"
	],

	'education_level' => [
		"None",
		"Pre-primary",
		"Primary (Class 1–8)",
		"Secondary (Form 1–4)",
		"Post-secondary (non-tertiary)", // e.g., certificate/diploma not at university
		"Tertiary - Certificate",
		"Tertiary - Diploma",
		"Tertiary - Bachelor's Degree",
		"Tertiary - Postgraduate Diploma",
		"Tertiary - Master's Degree",
		"Tertiary - Doctorate (PhD)",
		"Adult Education",
		"Other"
	],

	'bank' => [ 
		"057" => "Equity Bank",
		"010" => "Kenya Commercial Bank (KCB)",
		"040" => "Co-operative Bank",
		"068" => "Stanbic Bank",
		"020" => "Standard Chartered Bank",
		"030" => "Barclays Bank Kenya (now Absa)",
		"044" => "NIC Bank (now NCBA)",
		"068" => "CFC Stanbic Bank",
		"050" => "Diamond Trust Bank (DTB)",
		"054" => "Family Bank",
		"056" => "Prime Bank",
		"011" => "I&M Bank",
		"006" => "National Bank of Kenya (NBK)",
		"071" => "Bank of Africa Kenya",
		"074" => "Citibank Kenya",
		"072" => "Guardian Bank",
		"031" => "Consolidated Bank of Kenya (CBK)",
		"012" => "Development Bank of Kenya",
		"042" => "Bank of Baroda Kenya",
		"023" => "Habib Bank AG Zurich",
	],

	'ethnicity' => [
		1 => "Kikuyu",
		2 => "Luhya",
		3 => "Luo",
		4 => "Kalenjin",
		5 => "Kamba",
		6 => "Kisii",
		7 => "Meru",
		8 => "Embu",
		9 => "Mbeere",
		10 => "Tharaka",
		11 => "Mijikenda",
		12 => "Swahili",
		13 => "Taita",
		14 => "Taveta",
		15 => "Pokomo",
		16 => "Orma",
		17 => "Somali",
		18 => "Borana",
		19 => "Rendille",
		20 => "Gabra",
		21 => "Sakuye",
		22 => "Burji",
		23 => "Turkana",
		24 => "Samburu",
		25 => "El Molo",
		26 => "Maasai",
		27 => "Kuria",
		28 => "Suba",
		29 => "Nubian",
		30 => "Bajuni",
		31 => "Basuba",
		32 => "Kenyan Arabs",
		33 => "Kenyan Asians",
		34 => "Europeans (White Kenyans)",
		35 => "Americans",
		36 => "Other African",
		37 => "Other (non-African)",
		38 => "Ogiek",
		39 => "Dorobo",
		40 => "Ilchamus",
		41 => "Malakote",
		42 => "Saakuye",
		43 => "Shanbara",
		44 => "Boni"
	],

	'county' => [
		1 => "Mombasa",
		2 => "Kwale",
		3 => "Kilifi",
		4 => "Tana River",
		5 => "Lamu",
		6 => "Taita Taveta",
		7 => "Garissa",
		8 => "Wajir",
		9 => "Mandera",
		10 => "Marsabit",
		11 => "Isiolo",
		12 => "Meru",
		13 => "Tharaka-Nithi",
		14 => "Embu",
		15 => "Kitui",
		16 => "Machakos",
		17 => "Makueni",
		18 => "Nyandarua",
		19 => "Nyeri",
		20 => "Kirinyaga",
		21 => "Murang'a",
		22 => "Kiambu",
		23 => "Turkana",
		24 => "West Pokot",
		25 => "Samburu",
		26 => "Trans Nzoia",
		27 => "Uasin Gishu",
		28 => "Elgeyo Marakwet",
		29 => "Nandi",
		30 => "Baringo",
		31 => "Laikipia",
		32 => "Nakuru",
		33 => "Narok",
		34 => "Kajiado",
		35 => "Kericho",
		36 => "Bomet",
		37 => "Kakamega",
		38 => "Vihiga",
		39 => "Bungoma",
		40 => "Busia",
		41 => "Siaya",
		42 => "Kisumu",
		43 => "Homa Bay",
		44 => "Migori",
		45 => "Kisii",
		46 => "Nyamira",
		47 => "Nairobi"
	],

	'engagement_type' => ["Extended Service", "Local Contract", "Permanent", "Probation", "Secondment(out)", "Temporary", "Transfer-of-Service"],

	'job_group' => ["4", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N", "P", "R", "S", "T", "U"],

	'designation' => [ 
		"Accountant[1]",
		"Accountant[2]",
		"Advisor - Specialist[2a]",
		"Advisor - Specialist[2b]",
		"Advisor - Specialist[2d]",
		"Artisan Grade[2] - Building",
		"Assistant Accountant-General",
		"Assistant Director - HRM",
		"Assistant Director - ICT",
		"Assistant Director - Irrigation Water Managment",
		"Assistant Director - Land Reclamation",
		"Assistant Director - Office Administrative Services",
		"Assistant Director - Public Communications",
		"Assistant Director - Records Management",
		"Assistant Engineer [1] -Irrigation",
		"Assistant Engineer [2] -Irrigation",
		"Assistant Engineer[1] - Water & Sewarage",
		"Assistant Engineer[2] - Water & Sewarage",
		"Assistant Government Chemist",
		"Assistant Office Administrator[1]",
		"Assistant Superintendent - Gardens",
		"Cabinet Secretary",
		"Chargehand I Building",
		"Chargehand I Electrical",
		"Chargehand I Mechanical",
		"Chief Administrative Secretary",
		"Chief Clerical Officer - General Office Ser",
		"Chief Driver",
		"Chief Engineer - Water & Sewarage",
		"Chief Finance Officer",
		"Chief Geologist- Geological Survey",
		"Chief Ground Water Assistant",
		"Chief Principal Water Research Officer",
		"Chief State Counsel",
		"Chief Superintending Engineer - Irrigation",
		"Chief Superintending Engineer - Water & Sewarage",
		"Chief Superintending Engineer-Agriculture",
		"Chief Superintending Geologist - Geological",
		"Chief Superintending Hydrologist",
		"Cleaning Supervisor[1]",
		"Cleaning Supervisor[2a]",
		"Clerical Officer[1] - General Office Servic",
		"Clerical Officer[1] - Records",
		"Clerical Officer[2] - General Office Servic",
		"Deputy Accountant General",
		"Deputy Chief State Counsel",
		"Deputy Director - Information",
		"Deputy Director - Irrigation Water Management",
		"Deputy Director - Land Reclamation",
		"Deputy Director - Public Communications",
		"Deputy Director - Supply Chain Management S",
		"Deputy Director - Youth Development",
		"Deputy Government Chemist",
		"Director - Administration",
		"Director - HRM",
		"Director - Statistics",
		"Director - Water Resources",
		"Drilling Superintendent",
		"Driver[1]",
		"Driver[2]",
		"Economist [1]",
		"Finance Officer[2]",
		"Geologist[1] - Water",
		"HRM Assistant[1]",
		"HRM Assistant[2]",
		"HRM Assistant[3]",
		"HRM Officer[1]",
		"Hydrologist[1]",
		"ICT Officer[1]",
		"Irrigation Water Management Officer",
		"Land Reclamation Officer[1]",
		"Land Reclamation Officer[2]",
		"Mechanic Grade[1]",
		"Office Administrative Assistant[1]",
		"Office Administrative Assistant[3]",
		"Office Administrator[2]",
		"Pensions Assistant[3]",
		"Plant Operator[2]",
		"Principal Accountant",
		"Principal Assistant Office Administrator",
		"Principal Chemist",
		"Principal Clerical Officer - Accounts",
		"Principal Clerical Officer - General Office Service",
		"Principal Drilling Superintendent",
		"Principal Driver[1]",
		"Principal Driver[2]",
		"Principal Economist",
		"Principal Finance Officer",
		"Principal HRM Assistant",
		"Principal Hydrologist Assistant",
		"Principal ICT Officer",
		"Principal Irrigation Water Management Officer",
		"Principal Land Reclamation Officer",
		"Principal Land Survey Assistant",
		"Principal Land Surveyor",
		"Principal Records Management Officer",
		"Principal Secretary",
		"Principal State Counsel",
		"Principal Superintendent - Irrigation",
		"Principal Superintendent Electrical (MVP)",
		"Principal Superintendent Groundwater",
		"Principal Superintendent Water",
		"Principal Superintendent Water Engineering",
		"Principal Supply Chain Management Assistant",
		"Principal Water Bailiff",
		"Principal Water Research Officer",
		"Public Communications Assistant [1]",
		"Public Communications Assistant [2]",
		"Public Communications Assistant [3]",
		"Records Management Officer[1]",
		"Records Management Officer[2]",
		"Secretary - Water",
		"Secretary Irrigation",
		"Secretary[2]",
		"Senior Accountant",
		"Senior Adminitrative Assistant",
		"Senior Assistant County Commissioner",
		"Senior Assistant Office Administrator",
		"Senior Assistant Secretary",
		"Senior Chargehand Building",
		"Senior Chargehand Electrical",
		"Senior Chargehand Mechanical",
		"Senior Clerical Officer - Accounts",
		"Senior Clerical Officer - General Office Se",
		"Senior Deputy Director - Supply Chain Manag",
		"Senior Deputy Secretary",
		"Senior Drilling Inspector",
		"Senior Drilling Superintendent",
		"Senior Driver",
		"Senior Economist [1]",
		"Senior HRM Officer",
		"Senior Hydrologist Assistant",
		"Senior ICT Officer",
		"Senior Inspector Ground Water",
		"Senior Inspector Water Engineering",
		"Senior Inspectot Water and Sewerage",
		"Senior Irrigation Water Management Officer",
		"Senior Land Reclamation Officer",
		"Senior Land Survey Assistant",
		"Senior Principal Finance Officer",
		"Senior Principal Superintendent Mechanical",
		"Senior Principal Superintending Geologist-",
		"Senior Principal Superintending Hydrologist",
		"Senior Principal Suprintedent Water and Sewerage",
		"Senior Principal Water Research Officer[2]",
		"Senior Public Communications Officer",
		"Senior Records Management Officer",
		"Senior Superintendent - Irrigation",
		"Senior Superintendent Electrical (MVP)",
		"Senior Superintendent Groundwater",
		"Senior Superintendent Mechanical (MVP)",
		"Senior Superintendent Water",
		"Senior Superintendent Water Engineering",
		"Senior Superintending Engineer - Irrigation",
		"Senior Superintending Engineer - Water & Sewarage",
		"Senior Superintending Geologist - Geologica",
		"Senior Superintending Hydrologist",
		"Senior Supply Chain Management Assistant",
		"Senior Supply Chain Management Officer",
		"Senior Support Staff",
		"Senior Transboundary Water Resources Officer",
		"Senior Water Bailiff Assistant",
		"Senior Water Research Officer",
		"Superintendent Electrical (MVP)",
		"Superintendent Groundwater",
		"Superintendent Water",
		"Supply Chain Management Assistant[1]",
		"Supply Chain Management Assistant[3]",
		"Supply Chain Management Officer[1]",
		"Support Staff",
		"Support Staff Supervisor",
		"Under Secretary",
		"Water Bailiff Assistant[3]",
		"Water Bailiff[1]",
	],
];
